### ISSUE TITLE
大家遇到过 gbtmaker消息无法写入kafka的情况吗？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#179]
之前在物理机上没问题，拷贝到其他机器或者云服务器上就遇到一些问题。jobmaker中无法获取gbt，先前看日志gbtmaker中都有submit kafka 也没报错， 后来看kafka的topic发现都没传成功，请问大家这个是怎么调试？

**Comment by 200787128** [comment]
我也有同样的问题
接收端：
正常
/work/kafka/bin/kafka-console-consumer.sh --zookeeper=172.19.111.238:2181 --topic=RawGbt
Using the ConsoleConsumer with old consumer is deprecated and will be removed in a future major release. Consider using the new consumer by passing [bootstrap-server] instead of [zookeeper].
 test
haha
发送端测试
/work/kafka/bin/kafka-console-producer.sh --broker-list 172.19.111.238:9092 --sync --topic RawGbt
>test
>haha
gbtmaker.cfg
配置内容
gbtmaker = {
  rpcinterval = 10;
  is_check_zmq = true;
  rawgbt_topic = "RawGbt";
};

bitcoind = {
  zmq_addr = "tcp://172.19.111.238:1933";
  rpc_addr    = "http://172.19.111.238:19001";
  rpc_userpwd = "admin:123";
};
kafka = {
  brokers = "172.19.111.238:9092";
};
gbtmaker 启动日志显示
I1121 23:55:46.619457  5927 Kafka.cc:351] producer librdkafka version: 0.9.1
I1121 23:55:46.619864  5927 Kafka.cc:421] add brokers: 172.19.111.238:9092
I1121 23:55:46.619925  5927 Kafka.cc:428] create topic handle: RawGbt
I1121 23:55:46.653065  5927 GbtMaker.cc:88] bitcoind getblockchaininfo: {"result":{"chain":"regtest","blocks":212,"headers":212,"bestblockhash":"64df5a757abef6d0023a5860a67f359b2261222b480b9480467ad72f9059287a","difficulty":4.656542373906925e-10,"mediantime":1542624656,"verificationprogress":1,"initialblockdownload":false,"chainwork":"00000000000000000000000000000000000000000000000000000000000001aa","size_on_disk":67255,"pruned":false,"softforks":[{"id":"bip34","version":2,"reject":{"status":false}},{"id":"bip66","version":3,"reject":{"status":false}},{"id":"bip65","version":4,"reject":{"status":false}}],"bip9_softforks":{"csv":{"status":"started","bit":0,"startTime":0,"timeout":9223372036854775807,"since":144,"statistics":{"period":144,"threshold":108,"elapsed":69,"count":69,"possible":true}},"segwit":{"status":"active","startTime":-1,"timeout":9223372036854775807,"since":0}},"warnings":""},"error":null,"id":"1"}
I1121 23:55:47.653982  5927 GbtMaker.cc:186] gbt height: 213, prev_hash: 64df5a757abef6d0023a5860a67f359b2261222b480b9480467ad72f9059287a, coinbase_value: 2500000000, bits: 207fffff, mintime: 1542624657, version: 805306369|0x30000001, gbthash: f0e61ee20cce7aaa8e74eab3395e2050d9a8e659fd39e5980ad0e28977bca576
I1121 23:55:47.654036  5927 GbtMaker.cc:222] sumbit to Kafka, msg len: 1188
I1121 23:55:49.974197  5927 GbtMaker.cc:141] stop gbtmaker
I1121 23:55:49.985512  5932 GbtMaker.cc:272] stop thread listen to bitcoind

kafka提交失败 直接退出了 也不知道什么原因造成的失败

**Comment by 200787128** [comment]
kafka top 详情 单机模式 
/work/kafka/bin/kafka-topics.sh --zookeeper 172.19.111.238:2181 --describe --topic=RawGbt
Topic:RawGbt    PartitionCount:1        ReplicationFactor:1     Configs:retention.ms=21600000
        Topic: RawGbt   Partition: 0    Leader: 1       Replicas: 1     Isr: 1

**Comment by YihaoPeng** [comment]
你们使用的kafka版本是什么

**Comment by 200787128** [comment]
按照 wget https://mirrors.tuna.tsinghua.edu.cn/apache/kafka/0.11.0.2/kafka_2.11-0.11.0.2.tgz 安装的

**Comment by sslazio2009** [comment]
> 你们使用的kafka版本是什么

kafka_2.12-1.1.0-sources.jar 本机这个版本很少出现，主要一换其他机器或者云服务器就容易出现。              中国大陆地区阿里云服务器试用的也是1.10的版本

**Comment by 200787128** [comment]
之前配置 127.0.0.1 IP的时候 也是一样的 后来才换的内网IP，阿里云服务器 上的ubuntu 16.04系统。。kafka 控制台 发送消息 接收都可以。就是程序一跑 直接就停止。不知道从什么地方查原因

**Comment by sslazio2009** [comment]
I1122 13:45:01.510596  2756 GbtMaker.cc:173] gbt height: 551033, prev_hash: 000000000000000000248dc39b7cb11fe26d6dcb9a05adb9826671ec04b15cbe, coinbase_value: 1266704230, bits: 172a4e2f, mintime: 1542860527, version: 536870912|0x20000000, gbthash: 6c8823f2faee3620bf0a57bcaa45ff32f18f88ec0db56302de0028037933c2b6
I1122 13:45:01.546953  2756 GbtMaker.cc:209] sumbit to Kafka, msg len: 4077640
I1122 13:45:06.652987  2756 GbtMaker.cc:173] gbt height: 551033, prev_hash: 000000000000000000248dc39b7cb11fe26d6dcb9a05adb9826671ec04b15cbe, coinbase_value: 1266704230, bits: 172a4e2f, mintime: 1542860527, version: 536870912|0x20000000, gbthash: c041d848d2a231e9aaf0f5772ce68baa15ded001f1c558381254a1eb2a93e12c
I1122 13:45:06.689694  2756 GbtMaker.cc:209] sumbit to Kafka, msg len: 4077640
I1122 13:45:11.844048  2756 GbtMaker.cc:173] gbt height: 551033, prev_hash: 000000000000000000248dc39b7cb11fe26d6dcb9a05adb9826671ec04b15cbe, coinbase_value: 1267468665, bits: 172a4e2f, mintime: 1542860527, version: 536870912|0x20000000, gbthash: 2ae4dad481c72519f2897082695ef6de71a2f659a3ebfe443c5d119eafa1d008
I1122 13:45:11.880769  2756 GbtMaker.cc:209] sumbit to Kafka, msg len: 4090176
I1122 13:45:16.983641  2756 GbtMaker.cc:173] gbt height: 551033, prev_hash: 000000000000000000248dc39b7cb11fe26d6dcb9a05adb9826671ec04b15cbe, coinbase_value: 1267468665, bits: 172a4e2f, mintime: 1542860527, version: 536870912|0x20000000, gbthash: 4c503661bfa50d1afebcc284039d7148853a523e5da0b308c632f42f33d64978
I1122 13:45:17.020479  2756 GbtMaker.cc:209] sumbit to Kafka, msg len: 4090176
我的现象和他不同，我的日志里面一直都有上面的，也一直能跑不会崩，log也没报错，但是jobmaker就是一直是空的，试用了阿里云的kafka服务显示RawGbt数量很少，应该就是kafka没正常接收吧？其他topic也没啥就这个经常出问题，不知道是不是和size以及系统设置在有关？

**Comment by 200787128** [comment]
> Kafka的配置文件`server.properties`中有一个地方需要注意：
> 
> ```
> listeners=PLAINTEXT://<这里必须设置为你的网卡的IP，并且该IP要能让客户端正常访问>:9092
> ```
> 因为kafka客户端采用如下连接方式：
> 
> 1. 向一个 bootstrap server 查询特定 topic 的 leader。（bootstrap server 即 kafka.brokers 配置中的值。）
> 2. bootstrap server 将 topic leader 的 listeners 返回给客户端。
> 3. 客户端根据 listeners 连接具体 topic 的 leader。
> 
> 所以，如果`listeners`配置不正确（比如为`0.0.0.0`或者`127.0.0.1`等），则其他服务器上的客户端无法连接到该kafka。
> 测试方法：在其他服务器上使用kafka控制台消费器生产者和消费者命令发送/接收消息。

我把kafka调整了 127.0.0.1然后删除那个 log文件夹 kafka可以收到消息了 但是有新问题
日志
I1122 14:34:30.859721 19568 Kafka.cc:347] producer librdkafka version: 0.9.1
I1122 14:34:30.859848 19568 Kafka.cc:417] add brokers: 127.0.0.1:9092
I1122 14:34:30.859894 19568 Kafka.cc:424] create topic handle: RawGbt
I1122 14:34:30.892601 19568 BitcoinUtils.cc:134] getnetworkinfo: {"result":{"version":170000,"subversion":"/Satoshi:0.17.0/","protocolversion":70015,"localservices":"000000000000040d","localrelay":true,"timeoffset":0,"networkactive":true,"connections":8,"networks":[{"name":"ipv4","limited":false,"reachable":true,"proxy":"","proxy_randomize_credentials":false},{"name":"ipv6","limited":false,"reachable":true,"proxy":"","proxy_randomize_credentials":false},{"name":"onion","limited":true,"reachable":false,"proxy":"","proxy_randomize_credentials":false}],"relayfee":0.00001000,"incrementalfee":0.00001000,"localaddresses":[],"warnings":"Warning: unknown new rules activated (versionbit 28)"},"error":null,"id":"1"}
I1122 14:34:30.892829 19568 GbtMaker.cc:105] check bitcoind zmq, waiting for zmq message 'hashtx'...
I1122 14:34:31.171042 19568 GbtMaker.cc:119] bitcoind zmq recv hashtx: 2c25175b1a90211cad68d5fc6ac2005fcdfcee5e816d40306cfb8165ed45a570
I1122 14:34:32.175778 19568 GbtMaker.cc:177] gbt height: 1444596, prev_hash: 0000000000000137c06d9b3eeefa71579d838f2b1a25436fe97fbdddfeeeb8f1, coinbase_value: 79285437, bits: 1a015b3d, mintime: 1542865104, version: 536870912|0x20000000, gbthash: 33ee62b3a48e3081744af5570d0f765928f988a028111dae6014a7bf07b84901
I1122 14:34:32.176599 19568 GbtMaker.cc:213] sumbit to Kafka, msg len: 88108
I1122 14:34:33.034267 19568 GbtMaker.cc:132] stop gbtmaker
I1122 14:34:33.038097 19575 GbtMaker.cc:348] stop thread listen to bitcoind
这个代表 钱包 ZMQ 应该是通的吧。。这个看到sumbit to Kafka收到消息了 
但是还是停止了 估计跟zmq相关。

同样的执行命令  执行 1次 和 执行3次 得到的结果不一样 
I1122 14:34:28.710482 19556 GbtMakerMain.cc:96] BTC gbtmaker version 2.2.0-167ea27
I1122 14:34:28.710779 19556 Kafka.cc:347] producer librdkafka version: 0.9.1
I1122 14:34:28.710916 19556 Kafka.cc:417] add brokers: 127.0.0.1:9092
I1122 14:34:28.710959 19556 Kafka.cc:424] create topic handle: RawGbt
I1122 14:34:28.743888 19556 BitcoinUtils.cc:134] getnetworkinfo: {"result":{"version":170000,"subversion":"/Satoshi:0.17.0/","protocolversion":70015,"localservices":"000000000000040d","localrelay":true,"timeoffset":0,"networkactive":true,"connections":8,"networks":[{"name":"ipv4","limited":false,"reachable":true,"proxy":"","proxy_randomize_credentials":false},{"name":"ipv6","limited":false,"reachable":true,"proxy":"","proxy_randomize_credentials":false},{"name":"onion","limited":true,"reachable":false,"proxy":"","proxy_randomize_credentials":false}],"relayfee":0.00001000,"incrementalfee":0.00001000,"localaddresses":[],"warnings":"Warning: unknown new rules activated (versionbit 28)"},"error":null,"id":"1"}
I1122 14:34:28.744146 19556 GbtMaker.cc:105] check bitcoind zmq, waiting for zmq message 'hashtx'...
I1122 14:34:29.672323 19556 GbtMaker.cc:132] stop gbtmaker
E1122 14:34:29.672469 19556 GbtMaker.cc:110] bitcoind zmq recv exception: Interrupted system call
F1122 14:34:29.672803 19556 GbtMakerMain.cc:136] gbtmaker init failure 
有时候 是这个 错误 有时候 是上面的错误 

钱包的启动参数 
bitcoind -daemon -testnet -zmqpubhashtx=tcp://0.0.0.0:8331 -zmqpubhashblock=tcp://0.0.0.0:8331 -rpcallowip=0.0.0.0/0 -rpcport=18332 -rpcuser=admin -rpcpassword=123
有时候 zmq是通的有时候 就不通。。
配置里面 zmq使用的是 tcp://127.0.0.1:8331
