### ISSUE TITLE
what's the difference between statushttpd and slparser?

### ISSUE THREAD

**Issue by nono1008** [btccom/btcpool#90]
as we know, slparser parse the binary file which is logged from share_log, and save the worker info to the local_status_db; statushttpd consume the share_log and get some worker info to the local_db.
why not use the statushttpd to get all the info and save it to one db? what's the advantage of this framework? Thx.

**Comment by YihaoPeng** [comment]
Unlike the messages in kafka, sharelog files are non-volatile. So we can rerun slparser at any time to re-generate earnings of any date (`./slparser` without params will shows its usage).
This can be useful if something goes wrong with our database or program.

Finding historical messages from a specific moment (the beginning of a day) in Kafka is a bit more difficult. And, these messages may have been cleared due to expiration.

On the other hand, it is entirely feasible to generate real-time hashrate information by reading the sharelog file. So slparser can indeed include the feature of statshttpd.

The problem is that for a mining pool that scale like BTC.com, a single statshttpd process consumes 10GB of memory while the slparser only needs 300MB. slparser can be started and stopped easily. However, after statshttpd restarts, it takes up to half an hour to consume historical messages before the initial data can be given.

So it seems unwise to add any new functionality to statshttpd.

**Comment by nono1008** [comment]
Thank you very much for reply this thread!
you mention the "non-volatile" and "memory" are the main reasons for my question, right?
I agree with the first one.
"the current statshttpd needs to save all the user's shares within one hour in memory (clear shares that added one hour ago, then add the latest share at each time)."
in my opinion, statshttpd will not save the raw share info in memory and just save the statistics info as second and minute. 
waiting for your reply and thx.    :)

**Comment by nono1008** [comment]
i calculate the statistics infor, and got some data.
one workershare about 29k, 10w miner will occupy about 3G, and 30+ miners will occupy 10G.
yes, u r right~
thx again~

**Comment by YihaoPeng** [comment]
Yes, the "non-volatile" and "memory" are the main reasons for this question.

And I have an idea about optimizing memory usage now. Increasing the interval of `WorkerShares::acceptShareSec_` from 1 second to `flush_db_interval` seconds may reduce lots of the memory usage.
